# Generated by Django 3.0.4 on 2020-09-19 10:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('headoffice', 'Corporate Headoffice'), ('home', 'Home')], default='headoffice', max_length=20)),
                ('incident_description', models.CharField(max_length=200, verbose_name='Description')),
                ('date_time', models.DateTimeField(default=datetime.datetime.today, verbose_name='Date')),
                ('incident_Location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Incident Location')),
                ('intial_severity', models.CharField(choices=[('minor', 'minor'), ('moderate', 'moderate'), ('critical', 'critical')], max_length=20)),
                ('cause', models.CharField(max_length=200)),
                ('action_taken', models.CharField(max_length=200)),
                ('reported_by', models.CharField(max_length=50)),
                ('incident_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
